### ISSUE TITLE
Set max-len to 80 columns

### ISSUE THREAD

**Issue by mccraveiro** [pagarme/javascript-style-guide#10]
Airbnb's uses 100 columns as max length of a line however our experience using Github tells that 80 columns still the best setting.
It also ensures max readability and forces developers to write clean code.

**Comment by thalesmello** [comment]
What are the drawbacks of using 100 in spite of 80?

**Comment by mccraveiro** [comment]
For once, Github uses 80 columns on all visualizations. Therefore forcing 80 columns improves code reviews.

**Comment by thalesmello** [comment]
@mccraveiro That's not true. That actually depends on the resolution of your monitor.

If you "ctrl -" your browser, you will see more characters fit in the screen.

**Comment by thalesmello** [comment]
I'm actually agains using 80 characters.

100 is short enough.

If we contrain ourselves to 80 characters, it will be more difficult to use expressive names,
kind of forcing people to write shorter variable names, such as `m` or `f`.

100 sounds like the sweet spot.

**Comment by MarcoWorms** [comment]
I don't agree with you @thalesmello. 80 characters doesn't enforce shorter names, in javascript you can always break the line to not reach 80 characters unless your function name is gigantic which means it's a bad function name.

**Comment by MarcoWorms** [comment]
IMO 80 characters is a really good limit and unless you are messing with HTML you should probably never reach it with good identation pratices. Also, shorter overall code width means we can have more vertical splits in our monitors, I'm in favour of  80 chars width

**Comment by thalesmello** [comment]
80 characters is too short,
120 characters would be too long.

100 is just right.

Relevant discussions:
https://www.quora.com/Why-does-Google-Java-coding-style-guide-chose-maximum-of-100-characters-column-limit-per-line-why-not-120-just-curious-to-know
https://wincent.com/blog/on-the-80-column-limit

**Comment by MarcoWorms** [comment]
Could you show me an example of well writen javascript where 80 columns limit fail?

**Comment by derekstavis** [comment]
My personal preference is 80 columns, but I always try to keep at 72.

The first thing to have in mind is: Expressive names comes first.

Having this said, I like keeping at 80 to force myself to write less nested code. The only exception for **never** breaking the like are strings that I want to keep verbatim, as adding newlines could erroneously include additional spaces, tabs etc.

But let's expand to the main problem that we have today:

This is a code sample from one of our projects:
```
|--------------------------------------------------------------------------------------------------| 100
|------------------------------------------------------------------------------| 80

return res.send(400, responseHelper.singleErrorResponse(req, 'action_forbidden', null,`"Transação com status '${transaction.status}' não pode ser estornada`))
```

Yeah, looks pretty ugly. It helps if we format this way:

```
|--------------------------------------------------------------------------------------------------| 100
|------------------------------------------------------------------------------| 80
const { singleErrorResponse } = responseHelper

const responseBody = singleErrorResponse(
    req,
    'action_forbidden',
    null,
    `Transação com status '${transaction.status}' não pode ser estornada`
)

return res.send(400, responseBody)
```

With [beautiful API design](https://www.youtube.com/watch?v=loj3CLHovt0), we move that optional `null` argument to the end and just don't fill it:

```
|--------------------------------------------------------------------------------------------------| 100
|------------------------------------------------------------------------------| 80
const { singleErrorResponse } = responseHelper

const responseBody = singleErrorResponse(
  req,
  'action_forbidden',
  `Transação com status '${transaction.status}' não pode ser estornada`
)

return res.send(400, responseBody)
```

With this examples, I'd like to argument that it's more productive to have a constrain of 80 columns for most code and a standard way of breaking lines on function declaration/call, `class`, `if` and other possible constructs.

**Comment by mccraveiro** [comment]
@derekstavis you nailed it!

We should not be discussing if the technology we have today support 80 or more columns. Instead we should view 80 columns as a restriction that enforces better code. I personally have never seen a 80+ columns code that couldn't be refactored into cleaner code that uses less than 80 columns.

Side note: ESLint has support for strings that cannot be broken into more lines.

**Comment by thalesmello** [comment]
Splitting function calls across multiple lines is terrible, in IMHO. If makes it convenient to fit more arguments in a function call, which is bad design. Let me explain what I mean.

Consider the following example:
```js
// I want to write the following function implementation (present in the DataOps migration project).
// If I allow up to 100 characters, I could write everything comfortably in the same line.
|--------------------------------------------------------------------------------------------------| 100
|------------------------------------------------------------------------------| 80
async function run () {
  const template = await readFileAsync('./redshift_migrations/.migration_template.js', 'utf-8')
}

|--------------------------------------------------------------------------------------------------| 100
|------------------------------------------------------------------------------| 80
// If I were to use 80 characters, I would have two options:
async function run () {
  // Splitting in the arguments in separate lines, which feels quite weird, to be sincere
  const template = await readFileAsync(
    './redshift_migrations/.migration_template.js',
    'utf-8'
  )

  // Or extracting the argument in separate variables:
  const path = './redshift_migrations/.migration_template.js'
  const template = await readFileAsync(path, 'utf-8')

  // Which, in my opinion, is not worth it. The 100 characters version isn't that long, fits nicely in the screen monitor, and allows for more code to be written as a single line, without having to break everything into separate lines.
}
```

Let's work on @derekstavis "ugly" version of the example. IMHO, splitting in different lines yields bad results. In my opinion, a better approach would be one of the two approaches:
```js
|--------------------------------------------------------------------------------------------------| 100
|------------------------------------------------------------------------------| 80
const type = 'action_forbidden'
const param = null
const message =  `Transação com status '${transaction.status}' não pode ser estornada` // What a coincidence! Fits under 100 characters
const responseBody = singleErrorResponse(req, type, param, message)
// As a bonus, we get documentation.

// The second approach, even better IMHO, would be to change the interface of the function
// to take an object instead.
const responseBody = singleErrorResponse({
    req,
    type: 'action_forbidden',
    parameter: null,
    message: `Transação com status '${transaction.status}' não pode ser estornada`
})
```

**Comment by thalesmello** [comment]
My final point is that 100 characters is fine. The added 20 characters aren't much longer, still fits just right in the screen, and make people less tempted to split function calls into multiple lines.

**Comment by MarcoWorms** [comment]
See for yourself the examples you gave:

![screenshot from 2017-07-26 13-00-24](https://user-images.githubusercontent.com/7863230/28631069-6af89d10-7202-11e7-865e-dff95256b925.png)


I'm in the office's notebook and in fullscreen. Your 100 max width example is unreadable without scrolling, while the 80 one is completaly fine to read.

**Comment by derekstavis** [comment]
The problem @thalesmello is that in `async function run () { ...` example you already need to break lines. If someone ever resolves to create a `./redshift_migrations/.migration_template_join_table.js` the `utf-8` argument will render unreadable, even with 100 columns :)

**Comment by thalesmello** [comment]
@MarcoWorms 
![image](https://user-images.githubusercontent.com/1127394/28632745-f0e550c6-7207-11e7-8df8-67a2b9efdd8e.png)

Which browser are you using?

**Comment by thalesmello** [comment]
@derekstavis In my original example, no.

But, if in fact I get a longer variable name, I would just use:

```
async function run () {
  const path = './redshift_migrations/.migration_template_join_table.js'
  const template = await readFileAsync(path, 'utf-8')
}
```

**Comment by MarcoWorms** [comment]
@thalesmello it's a normal chrome

fullscreen example

![image](https://user-images.githubusercontent.com/7863230/28634913-1ad21b9c-720f-11e7-83d6-754084aebb55.png)

**Comment by thalesmello** [comment]
Considering the arguments provided, I now agree with having a max of 80 columns.
